import { config } from 'dotenv';
import { neonDB, Match, Player } from '../lib/neon-db';

// Load environment variables
config({ path: '.env.local' });

// Dummy data for 5 matches (10 teams total)
const dummyMatches: Omit<Match, 'id'>[] = [
  {
    team_name: 'India vs Australia',
    match_venue: 'Wankhede Stadium, Mumbai',
    match_date: new Date('2025-07-15'),
    match_format: 'T20',
    is_active: true,
    start_time: '19:30',
    end_time: '23:00',
    is_upcoming: true,
    status: 'Scheduled',
    venue_condition: 'Dry',
    pitch_condition: 'Flat',
    weather_condition: 'Clear'
  },
  {
    team_name: 'England vs Pakistan',
    match_venue: 'Lord\'s Cricket Ground, London',
    match_date: new Date('2025-07-16'),
    match_format: 'ODI',
    is_active: true,
    start_time: '14:30',
    end_time: '22:30',
    is_upcoming: true,
    status: 'Scheduled',
    venue_condition: 'Neutral',
    pitch_condition: 'Seam-friendly',
    weather_condition: 'Overcast'
  },
  {
    team_name: 'South Africa vs New Zealand',
    match_venue: 'Newlands, Cape Town',
    match_date: new Date('2025-07-17'),
    match_format: 'Test',
    is_active: true,
    start_time: '10:00',
    end_time: '17:00',
    is_upcoming: true,
    status: 'Scheduled',
    venue_condition: 'Dry',
    pitch_condition: 'Bouncy',
    weather_condition: 'Clear'
  },
  {
    team_name: 'West Indies vs Sri Lanka',
    match_venue: 'Kensington Oval, Barbados',
    match_date: new Date('2025-07-18'),
    match_format: 'T20',
    is_active: true,
    start_time: '20:00',
    end_time: '23:30',
    is_upcoming: true,
    status: 'Scheduled',
    venue_condition: 'Humid',
    pitch_condition: 'Spin-friendly',
    weather_condition: 'Humid'
  },
  {
    team_name: 'Bangladesh vs Afghanistan',
    match_venue: 'Shere Bangla National Stadium, Dhaka',
    match_date: new Date('2025-07-19'),
    match_format: 'ODI',
    is_active: true,
    start_time: '15:00',
    end_time: '23:00',
    is_upcoming: true,
    status: 'Scheduled',
    venue_condition: 'Wet',
    pitch_condition: 'Spin-friendly',
    weather_condition: 'Rainy'
  }
];

// Dummy players data (15 players per team, 11 active + 4 inactive)
const dummyPlayers: Omit<Player, 'id'>[] = [
  // India Team (15 players - 11 active, 4 inactive)
  { name: 'V Kohli', full_name: 'Virat Kohli', team_name: 'India', player_role: 'BAT', credits: 11.5, selection_percentage: 85.2, points: 58, is_playing_today: true, country: 'India', batting_style: 'RH', bowling_style: 'RH', dream_team_percentage: 78.5, recent_form_rating: 0.92, consistency_score: 0.88, versatility_score: 0.95, injury_risk_score: 8, venue_performance: 0.87, pitch_suitability: 0.91, weather_adaptability: 0.85, opposition_strength: 0.89, head_to_head_record: 0.86, captain_potential: 0.94, ownership_projection: 45.2, price_efficiency: 0.76, upset_potential: 0.35, recent_match_points: [68, 52, 74, 45, 61], match_format_preference: 'T20', playing_conditions_preference: 'Day' },
  { name: 'R Sharma', full_name: 'Rohit Sharma', team_name: 'India', player_role: 'BAT', credits: 11.0, selection_percentage: 78.5, points: 52, is_playing_today: true, country: 'India', batting_style: 'RH', bowling_style: 'RH', dream_team_percentage: 72.3, recent_form_rating: 0.85, consistency_score: 0.82, versatility_score: 0.88, injury_risk_score: 7, venue_performance: 0.81, pitch_suitability: 0.86, weather_adaptability: 0.79, opposition_strength: 0.83, head_to_head_record: 0.80, captain_potential: 0.91, ownership_projection: 42.8, price_efficiency: 0.71, upset_potential: 0.38, recent_match_points: [58, 47, 65, 38, 52], match_format_preference: 'ODI', playing_conditions_preference: 'Day' },
  { name: 'J Bumrah', full_name: 'Jasprit Bumrah', team_name: 'India', player_role: 'BWL', credits: 10.5, selection_percentage: 72.3, points: 45, is_playing_today: true, country: 'India', batting_style: 'RH', bowling_style: 'RH', dream_team_percentage: 65.8, recent_form_rating: 0.89, consistency_score: 0.91, versatility_score: 0.85, injury_risk_score: 6, venue_performance: 0.88, pitch_suitability: 0.92, weather_adaptability: 0.87, opposition_strength: 0.90, head_to_head_record: 0.85, captain_potential: 0.75, ownership_projection: 38.6, price_efficiency: 0.68, upset_potential: 0.42, recent_match_points: [52, 41, 58, 35, 45], match_format_preference: 'T20', playing_conditions_preference: 'Night' },
  { name: 'R Pant', full_name: 'Rishabh Pant', team_name: 'India', player_role: 'WK', credits: 10.0, selection_percentage: 68.7, points: 41, is_playing_today: true, country: 'India', batting_style: 'LH', bowling_style: 'RH', dream_team_percentage: 58.9, recent_form_rating: 0.78, consistency_score: 0.72, versatility_score: 0.81, injury_risk_score: 7, venue_performance: 0.75, pitch_suitability: 0.79, weather_adaptability: 0.73, opposition_strength: 0.76, head_to_head_record: 0.74, captain_potential: 0.68, ownership_projection: 35.4, price_efficiency: 0.65, upset_potential: 0.51, recent_match_points: [48, 32, 51, 28, 41], match_format_preference: 'Test', playing_conditions_preference: 'Day' },
  { name: 'H Pandya', full_name: 'Hardik Pandya', team_name: 'India', player_role: 'AR', credits: 9.5, selection_percentage: 65.1, points: 38, is_playing_today: true, country: 'India', batting_style: 'RH', bowling_style: 'RH', dream_team_percentage: 52.4, recent_form_rating: 0.81, consistency_score: 0.76, versatility_score: 0.89, injury_risk_score: 5, venue_performance: 0.78, pitch_suitability: 0.83, weather_adaptability: 0.80, opposition_strength: 0.79, head_to_head_record: 0.77, captain_potential: 0.84, ownership_projection: 32.1, price_efficiency: 0.63, upset_potential: 0.47, recent_match_points: [42, 35, 48, 31, 38], match_format_preference: 'T20', playing_conditions_preference: 'Night' },
  { name: 'K Rahul', full_name: 'KL Rahul', team_name: 'India', player_role: 'WK', credits: 9.0, selection_percentage: 58.9, points: 35, is_playing_today: true, country: 'India', batting_style: 'RH', bowling_style: 'RH', dream_team_percentage: 46.7, recent_form_rating: 0.74, consistency_score: 0.79, versatility_score: 0.86, injury_risk_score: 8, venue_performance: 0.72, pitch_suitability: 0.77, weather_adaptability: 0.75, opposition_strength: 0.73, head_to_head_record: 0.71, captain_potential: 0.72, ownership_projection: 28.9, price_efficiency: 0.61, upset_potential: 0.43, recent_match_points: [38, 32, 42, 28, 35], match_format_preference: 'ODI', playing_conditions_preference: 'Day' },
  { name: 'R Ashwin', full_name: 'Ravichandran Ashwin', team_name: 'India', player_role: 'BWL', credits: 8.5, selection_percentage: 45.6, points: 32, is_playing_today: true, country: 'India', batting_style: 'RH', bowling_style: 'RH', dream_team_percentage: 38.2, recent_form_rating: 0.77, consistency_score: 0.84, versatility_score: 0.82, injury_risk_score: 9, venue_performance: 0.80, pitch_suitability: 0.89, weather_adaptability: 0.78, opposition_strength: 0.81, head_to_head_record: 0.79, captain_potential: 0.76, ownership_projection: 25.6, price_efficiency: 0.59, upset_potential: 0.39, recent_match_points: [35, 28, 38, 25, 32], match_format_preference: 'Test', playing_conditions_preference: 'Day' },
  { name: 'S Gill', full_name: 'Shubman Gill', team_name: 'India', player_role: 'BAT', credits: 8.0, selection_percentage: 42.3, points: 28, is_playing_today: true, country: 'India', batting_style: 'RH', bowling_style: 'RH', dream_team_percentage: 35.6, recent_form_rating: 0.83, consistency_score: 0.75, versatility_score: 0.79, injury_risk_score: 9, venue_performance: 0.76, pitch_suitability: 0.81, weather_adaptability: 0.74, opposition_strength: 0.77, head_to_head_record: 0.73, captain_potential: 0.65, ownership_projection: 22.8, price_efficiency: 0.55, upset_potential: 0.58, recent_match_points: [32, 24, 35, 22, 28], match_format_preference: 'ODI', playing_conditions_preference: 'Day' },
  { name: 'Y Chahal', full_name: 'Yuzvendra Chahal', team_name: 'India', player_role: 'BWL', credits: 7.5, selection_percentage: 38.7, points: 25, is_playing_today: true, country: 'India', batting_style: 'RH', bowling_style: 'LH', dream_team_percentage: 29.8, recent_form_rating: 0.71, consistency_score: 0.68, versatility_score: 0.75, injury_risk_score: 8, venue_performance: 0.73, pitch_suitability: 0.84, weather_adaptability: 0.69, opposition_strength: 0.72, head_to_head_record: 0.70, captain_potential: 0.45, ownership_projection: 19.4, price_efficiency: 0.52, upset_potential: 0.46, recent_match_points: [28, 22, 31, 19, 25], match_format_preference: 'T20', playing_conditions_preference: 'Night' },
  { name: 'M Shami', full_name: 'Mohammed Shami', team_name: 'India', player_role: 'BWL', credits: 7.0, selection_percentage: 35.2, points: 22, is_playing_today: true, country: 'India', batting_style: 'RH', bowling_style: 'RH', dream_team_percentage: 25.4, recent_form_rating: 0.75, consistency_score: 0.81, versatility_score: 0.78, injury_risk_score: 7, venue_performance: 0.77, pitch_suitability: 0.85, weather_adaptability: 0.76, opposition_strength: 0.78, head_to_head_record: 0.74, captain_potential: 0.52, ownership_projection: 16.8, price_efficiency: 0.49, upset_potential: 0.41, recent_match_points: [25, 19, 28, 16, 22], match_format_preference: 'Test', playing_conditions_preference: 'Day' },
  { name: 'R Jadeja', full_name: 'Ravindra Jadeja', team_name: 'India', player_role: 'AR', credits: 8.5, selection_percentage: 48.9, points: 30, is_playing_today: true, country: 'India', batting_style: 'LH', bowling_style: 'LH', dream_team_percentage: 41.3, recent_form_rating: 0.79, consistency_score: 0.86, versatility_score: 0.91, injury_risk_score: 8, venue_performance: 0.82, pitch_suitability: 0.88, weather_adaptability: 0.81, opposition_strength: 0.83, head_to_head_record: 0.80, captain_potential: 0.78, ownership_projection: 24.7, price_efficiency: 0.56, upset_potential: 0.37, recent_match_points: [33, 27, 36, 24, 30], match_format_preference: 'Test', playing_conditions_preference: 'Day' },
  // Inactive players
  { name: 'I Kishan', full_name: 'Ishan Kishan', team_name: 'India', player_role: 'WK', credits: 6.5, selection_percentage: 15.2, points: 18, is_playing_today: false, country: 'India', batting_style: 'LH', bowling_style: 'RH', dream_team_percentage: 12.8, recent_form_rating: 0.62, consistency_score: 0.58, versatility_score: 0.67, injury_risk_score: 9, venue_performance: 0.61, pitch_suitability: 0.65, weather_adaptability: 0.59, opposition_strength: 0.63, head_to_head_record: 0.60, captain_potential: 0.45, ownership_projection: 8.2, price_efficiency: 0.44, upset_potential: 0.67, recent_match_points: [21, 15, 24, 12, 18], match_format_preference: 'T20', playing_conditions_preference: 'Night' },
  { name: 'P Krishna', full_name: 'Prasidh Krishna', team_name: 'India', player_role: 'BWL', credits: 6.0, selection_percentage: 12.8, points: 15, is_playing_today: false, country: 'India', batting_style: 'RH', bowling_style: 'RH', dream_team_percentage: 8.9, recent_form_rating: 0.58, consistency_score: 0.61, versatility_score: 0.64, injury_risk_score: 7, venue_performance: 0.60, pitch_suitability: 0.68, weather_adaptability: 0.57, opposition_strength: 0.59, head_to_head_record: 0.56, captain_potential: 0.35, ownership_projection: 6.4, price_efficiency: 0.40, upset_potential: 0.72, recent_match_points: [18, 12, 21, 9, 15], match_format_preference: 'ODI', playing_conditions_preference: 'Day' },
  { name: 'S Samson', full_name: 'Sanju Samson', team_name: 'India', player_role: 'WK', credits: 6.5, selection_percentage: 18.5, points: 20, is_playing_today: false, country: 'India', batting_style: 'RH', bowling_style: 'RH', dream_team_percentage: 15.2, recent_form_rating: 0.65, consistency_score: 0.55, versatility_score: 0.69, injury_risk_score: 8, venue_performance: 0.63, pitch_suitability: 0.67, weather_adaptability: 0.61, opposition_strength: 0.64, head_to_head_record: 0.62, captain_potential: 0.58, ownership_projection: 9.8, price_efficiency: 0.49, upset_potential: 0.78, recent_match_points: [23, 17, 26, 14, 20], match_format_preference: 'T20', playing_conditions_preference: 'Night' },
  { name: 'W Sundar', full_name: 'Washington Sundar', team_name: 'India', player_role: 'AR', credits: 6.0, selection_percentage: 14.7, points: 16, is_playing_today: false, country: 'India', batting_style: 'LH', bowling_style: 'RH', dream_team_percentage: 11.6, recent_form_rating: 0.60, consistency_score: 0.64, versatility_score: 0.71, injury_risk_score: 9, venue_performance: 0.62, pitch_suitability: 0.70, weather_adaptability: 0.58, opposition_strength: 0.61, head_to_head_record: 0.59, captain_potential: 0.42, ownership_projection: 7.3, price_efficiency: 0.43, upset_potential: 0.69, recent_match_points: [19, 13, 22, 10, 16], match_format_preference: 'Test', playing_conditions_preference: 'Day' },

  // Australia Team (15 players - 11 active, 4 inactive)
  { name: 'S Smith', full_name: 'Steven Smith', team_name: 'Australia', player_role: 'BAT', credits: 11.0, selection_percentage: 82.1, points: 55, is_playing_today: true, country: 'Australia', batting_style: 'RH', bowling_style: 'LH', dream_team_percentage: 75.6, recent_form_rating: 0.90, consistency_score: 0.94, versatility_score: 0.92, injury_risk_score: 8, venue_performance: 0.88, pitch_suitability: 0.93, weather_adaptability: 0.86, opposition_strength: 0.91, head_to_head_record: 0.87, captain_potential: 0.89, ownership_projection: 43.8, price_efficiency: 0.75, upset_potential: 0.31, recent_match_points: [62, 48, 68, 44, 55], match_format_preference: 'Test', playing_conditions_preference: 'Day' },
  { name: 'D Warner', full_name: 'David Warner', team_name: 'Australia', player_role: 'BAT', credits: 10.5, selection_percentage: 76.8, points: 48, is_playing_today: true, country: 'Australia', batting_style: 'LH', bowling_style: 'RH', dream_team_percentage: 68.9, recent_form_rating: 0.84, consistency_score: 0.80, versatility_score: 0.87, injury_risk_score: 7, venue_performance: 0.82, pitch_suitability: 0.85, weather_adaptability: 0.81, opposition_strength: 0.84, head_to_head_record: 0.83, captain_potential: 0.86, ownership_projection: 38.6, price_efficiency: 0.69, upset_potential: 0.36, recent_match_points: [52, 44, 58, 38, 48], match_format_preference: 'T20', playing_conditions_preference: 'Day' },
  { name: 'P Cummins', full_name: 'Pat Cummins', team_name: 'Australia', player_role: 'BWL', credits: 10.0, selection_percentage: 69.5, points: 42, is_playing_today: true, country: 'Australia', batting_style: 'RH', bowling_style: 'RH', dream_team_percentage: 62.3, recent_form_rating: 0.87, consistency_score: 0.89, versatility_score: 0.83, injury_risk_score: 8, venue_performance: 0.85, pitch_suitability: 0.90, weather_adaptability: 0.84, opposition_strength: 0.88, head_to_head_record: 0.86, captain_potential: 0.92, ownership_projection: 35.2, price_efficiency: 0.67, upset_potential: 0.39, recent_match_points: [48, 36, 52, 33, 42], match_format_preference: 'Test', playing_conditions_preference: 'Day' },
  { name: 'A Carey', full_name: 'Alex Carey', team_name: 'Australia', player_role: 'WK', credits: 8.5, selection_percentage: 52.3, points: 33, is_playing_today: true, country: 'Australia', batting_style: 'LH', bowling_style: 'RH', dream_team_percentage: 44.8, recent_form_rating: 0.72, consistency_score: 0.75, versatility_score: 0.77, injury_risk_score: 9, venue_performance: 0.71, pitch_suitability: 0.76, weather_adaptability: 0.73, opposition_strength: 0.74, head_to_head_record: 0.72, captain_potential: 0.71, ownership_projection: 26.8, price_efficiency: 0.62, upset_potential: 0.48, recent_match_points: [38, 28, 41, 25, 33], match_format_preference: 'ODI', playing_conditions_preference: 'Day' },
  { name: 'G Maxwell', full_name: 'Glenn Maxwell', team_name: 'Australia', player_role: 'AR', credits: 9.0, selection_percentage: 58.7, points: 36, is_playing_today: true, country: 'Australia', batting_style: 'RH', bowling_style: 'RH', dream_team_percentage: 48.2, recent_form_rating: 0.76, consistency_score: 0.68, versatility_score: 0.88, injury_risk_score: 6, venue_performance: 0.74, pitch_suitability: 0.79, weather_adaptability: 0.77, opposition_strength: 0.75, head_to_head_record: 0.73, captain_potential: 0.82, ownership_projection: 29.4, price_efficiency: 0.64, upset_potential: 0.63, recent_match_points: [42, 30, 45, 27, 36], match_format_preference: 'T20', playing_conditions_preference: 'Night' },
  { name: 'M Labuschagne', full_name: 'Marnus Labuschagne', team_name: 'Australia', player_role: 'BAT', credits: 9.5, selection_percentage: 61.2, points: 39, is_playing_today: true, country: 'Australia', batting_style: 'RH', bowling_style: 'LH', dream_team_percentage: 51.6, recent_form_rating: 0.85, consistency_score: 0.88, versatility_score: 0.81, injury_risk_score: 9, venue_performance: 0.83, pitch_suitability: 0.87, weather_adaptability: 0.80, opposition_strength: 0.84, head_to_head_record: 0.81, captain_potential: 0.74, ownership_projection: 31.2, price_efficiency: 0.66, upset_potential: 0.41, recent_match_points: [45, 33, 48, 30, 39], match_format_preference: 'Test', playing_conditions_preference: 'Day' },
  { name: 'J Hazlewood', full_name: 'Josh Hazlewood', team_name: 'Australia', player_role: 'BWL', credits: 8.0, selection_percentage: 44.8, points: 28, is_playing_today: true, country: 'Australia', batting_style: 'RH', bowling_style: 'RH', dream_team_percentage: 36.9, recent_form_rating: 0.79, consistency_score: 0.83, versatility_score: 0.76, injury_risk_score: 7, venue_performance: 0.78, pitch_suitability: 0.84, weather_adaptability: 0.77, opposition_strength: 0.80, head_to_head_record: 0.79, captain_potential: 0.58, ownership_projection: 22.4, price_efficiency: 0.56, upset_potential: 0.44, recent_match_points: [32, 24, 35, 21, 28], match_format_preference: 'Test', playing_conditions_preference: 'Day' },
  { name: 'T Head', full_name: 'Travis Head', team_name: 'Australia', player_role: 'BAT', credits: 8.5, selection_percentage: 47.6, points: 31, is_playing_today: true, country: 'Australia', batting_style: 'LH', bowling_style: 'RH', dream_team_percentage: 39.2, recent_form_rating: 0.81, consistency_score: 0.73, versatility_score: 0.84, injury_risk_score: 8, venue_performance: 0.79, pitch_suitability: 0.82, weather_adaptability: 0.78, opposition_strength: 0.80, head_to_head_record: 0.76, captain_potential: 0.67, ownership_projection: 24.6, price_efficiency: 0.58, upset_potential: 0.52, recent_match_points: [36, 26, 39, 23, 31], match_format_preference: 'ODI', playing_conditions_preference: 'Day' },
  { name: 'A Zampa', full_name: 'Adam Zampa', team_name: 'Australia', player_role: 'BWL', credits: 7.5, selection_percentage: 41.3, points: 26, is_playing_today: true, country: 'Australia', batting_style: 'RH', bowling_style: 'RH', dream_team_percentage: 33.6, recent_form_rating: 0.74, consistency_score: 0.77, versatility_score: 0.79, injury_risk_score: 8, venue_performance: 0.76, pitch_suitability: 0.86, weather_adaptability: 0.72, opposition_strength: 0.75, head_to_head_record: 0.73, captain_potential: 0.51, ownership_projection: 20.8, price_efficiency: 0.55, upset_potential: 0.49, recent_match_points: [30, 22, 33, 19, 26], match_format_preference: 'ODI', playing_conditions_preference: 'Day' },
  { name: 'M Starc', full_name: 'Mitchell Starc', team_name: 'Australia', player_role: 'BWL', credits: 8.5, selection_percentage: 46.9, points: 29, is_playing_today: true, country: 'Australia', batting_style: 'LH', bowling_style: 'LH', dream_team_percentage: 38.7, recent_form_rating: 0.77, consistency_score: 0.80, versatility_score: 0.82, injury_risk_score: 7, venue_performance: 0.79, pitch_suitability: 0.85, weather_adaptability: 0.81, opposition_strength: 0.78, head_to_head_record: 0.77, captain_potential: 0.62, ownership_projection: 23.4, price_efficiency: 0.54, upset_potential: 0.45, recent_match_points: [33, 25, 36, 22, 29], match_format_preference: 'ODI', playing_conditions_preference: 'Day' },
  { name: 'C Green', full_name: 'Cameron Green', team_name: 'Australia', player_role: 'AR', credits: 7.0, selection_percentage: 38.5, points: 24, is_playing_today: true, country: 'Australia', batting_style: 'RH', bowling_style: 'RH', dream_team_percentage: 31.4, recent_form_rating: 0.70, consistency_score: 0.74, versatility_score: 0.81, injury_risk_score: 8, venue_performance: 0.72, pitch_suitability: 0.77, weather_adaptability: 0.70, opposition_strength: 0.73, head_to_head_record: 0.71, captain_potential: 0.64, ownership_projection: 18.6, price_efficiency: 0.51, upset_potential: 0.56, recent_match_points: [28, 20, 31, 17, 24], match_format_preference: 'Test', playing_conditions_preference: 'Day' },
  // Inactive players
  { name: 'M Marsh', full_name: 'Mitchell Marsh', team_name: 'Australia', player_role: 'AR', credits: 6.5, selection_percentage: 22.1, points: 19, is_playing_today: false, country: 'Australia', batting_style: 'RH', bowling_style: 'RH', dream_team_percentage: 17.8, recent_form_rating: 0.64, consistency_score: 0.67, versatility_score: 0.75, injury_risk_score: 6, venue_performance: 0.66, pitch_suitability: 0.71, weather_adaptability: 0.65, opposition_strength: 0.67, head_to_head_record: 0.64, captain_potential: 0.58, ownership_projection: 11.2, price_efficiency: 0.46, upset_potential: 0.71, recent_match_points: [22, 16, 25, 13, 19], match_format_preference: 'T20', playing_conditions_preference: 'Night' },
  { name: 'N Lyon', full_name: 'Nathan Lyon', team_name: 'Australia', player_role: 'BWL', credits: 6.0, selection_percentage: 18.7, points: 17, is_playing_today: false, country: 'Australia', batting_style: 'RH', bowling_style: 'RH', dream_team_percentage: 14.2, recent_form_rating: 0.61, consistency_score: 0.72, versatility_score: 0.68, injury_risk_score: 9, venue_performance: 0.70, pitch_suitability: 0.82, weather_adaptability: 0.62, opposition_strength: 0.69, head_to_head_record: 0.67, captain_potential: 0.48, ownership_projection: 9.4, price_efficiency: 0.45, upset_potential: 0.68, recent_match_points: [20, 14, 23, 11, 17], match_format_preference: 'Test', playing_conditions_preference: 'Day' },
  { name: 'M Short', full_name: 'Matt Short', team_name: 'Australia', player_role: 'BAT', credits: 6.0, selection_percentage: 16.3, points: 14, is_playing_today: false, country: 'Australia', batting_style: 'RH', bowling_style: 'RH', dream_team_percentage: 12.6, recent_form_rating: 0.58, consistency_score: 0.63, versatility_score: 0.71, injury_risk_score: 9, venue_performance: 0.60, pitch_suitability: 0.66, weather_adaptability: 0.59, opposition_strength: 0.61, head_to_head_record: 0.58, captain_potential: 0.41, ownership_projection: 8.2, price_efficiency: 0.37, upset_potential: 0.84, recent_match_points: [17, 11, 20, 8, 14], match_format_preference: 'T20', playing_conditions_preference: 'Night' },
  { name: 'S Abbott', full_name: 'Sean Abbott', team_name: 'Australia', player_role: 'BWL', credits: 5.5, selection_percentage: 12.8, points: 12, is_playing_today: false, country: 'Australia', batting_style: 'RH', bowling_style: 'RH', dream_team_percentage: 9.8, recent_form_rating: 0.55, consistency_score: 0.60, versatility_score: 0.65, injury_risk_score: 8, venue_performance: 0.57, pitch_suitability: 0.64, weather_adaptability: 0.56, opposition_strength: 0.58, head_to_head_record: 0.55, captain_potential: 0.33, ownership_projection: 6.4, price_efficiency: 0.35, upset_potential: 0.78, recent_match_points: [15, 9, 18, 6, 12], match_format_preference: 'ODI', playing_conditions_preference: 'Day' },

  // England Team (15 players - 11 active, 4 inactive)
  { name: 'J Root', full_name: 'Joe Root', team_name: 'England', player_role: 'BAT', credits: 10.5, selection_percentage: 78.9, points: 51, is_playing_today: true, country: 'England', batting_style: 'RH', bowling_style: 'RH', dream_team_percentage: 69.2, recent_form_rating: 0.88, consistency_score: 0.92, versatility_score: 0.91, injury_risk_score: 8, venue_performance: 0.85, pitch_suitability: 0.89, weather_adaptability: 0.84, opposition_strength: 0.87, head_to_head_record: 0.85, captain_potential: 0.88, ownership_projection: 39.6, price_efficiency: 0.73, upset_potential: 0.33, recent_match_points: [58, 44, 61, 41, 51], match_format_preference: 'Test', playing_conditions_preference: 'Day' },
  { name: 'B Stokes', full_name: 'Ben Stokes', team_name: 'England', player_role: 'AR', credits: 10.0, selection_percentage: 72.6, points: 46, is_playing_today: true, country: 'England', batting_style: 'LH', bowling_style: 'RH', dream_team_percentage: 61.8, recent_form_rating: 0.83, consistency_score: 0.78, versatility_score: 0.94, injury_risk_score: 6, venue_performance: 0.81, pitch_suitability: 0.86, weather_adaptability: 0.82, opposition_strength: 0.85, head_to_head_record: 0.83, captain_potential: 0.95, ownership_projection: 36.3, price_efficiency: 0.69, upset_potential: 0.41, recent_match_points: [52, 40, 55, 37, 46], match_format_preference: 'Test', playing_conditions_preference: 'Day' },
  { name: 'J Buttler', full_name: 'Jos Buttler', team_name: 'England', player_role: 'WK', credits: 9.5, selection_percentage: 68.4, points: 43, is_playing_today: true, country: 'England', batting_style: 'RH', bowling_style: 'RH', dream_team_percentage: 56.9, recent_form_rating: 0.80, consistency_score: 0.74, versatility_score: 0.89, injury_risk_score: 7, venue_performance: 0.78, pitch_suitability: 0.82, weather_adaptability: 0.79, opposition_strength: 0.81, head_to_head_record: 0.78, captain_potential: 0.84, ownership_projection: 34.2, price_efficiency: 0.68, upset_potential: 0.45, recent_match_points: [49, 37, 52, 34, 43], match_format_preference: 'T20', playing_conditions_preference: 'Night' },
  { name: 'H Brook', full_name: 'Harry Brook', team_name: 'England', player_role: 'BAT', credits: 9.0, selection_percentage: 61.7, points: 38, is_playing_today: true, country: 'England', batting_style: 'RH', bowling_style: 'RH', dream_team_percentage: 49.3, recent_form_rating: 0.84, consistency_score: 0.71, versatility_score: 0.83, injury_risk_score: 9, venue_performance: 0.82, pitch_suitability: 0.85, weather_adaptability: 0.80, opposition_strength: 0.83, head_to_head_record: 0.79, captain_potential: 0.72, ownership_projection: 30.8, price_efficiency: 0.63, upset_potential: 0.56, recent_match_points: [44, 32, 47, 29, 38], match_format_preference: 'Test', playing_conditions_preference: 'Day' },
  { name: 'J Anderson', full_name: 'James Anderson', team_name: 'England', player_role: 'BWL', credits: 8.5, selection_percentage: 55.2, points: 34, is_playing_today: true, country: 'England', batting_style: 'LH', bowling_style: 'RH', dream_team_percentage: 44.6, recent_form_rating: 0.78, consistency_score: 0.89, versatility_score: 0.76, injury_risk_score: 7, venue_performance: 0.83, pitch_suitability: 0.91, weather_adaptability: 0.81, opposition_strength: 0.84, head_to_head_record: 0.86, captain_potential: 0.69, ownership_projection: 27.6, price_efficiency: 0.64, upset_potential: 0.38, recent_match_points: [40, 28, 43, 25, 34], match_format_preference: 'Test', playing_conditions_preference: 'Day' },
  { name: 'M Wood', full_name: 'Mark Wood', team_name: 'England', player_role: 'BWL', credits: 8.0, selection_percentage: 48.6, points: 31, is_playing_today: true, country: 'England', batting_style: 'LH', bowling_style: 'RH', dream_team_percentage: 38.9, recent_form_rating: 0.75, consistency_score: 0.79, versatility_score: 0.81, injury_risk_score: 5, venue_performance: 0.77, pitch_suitability: 0.84, weather_adaptability: 0.78, opposition_strength: 0.79, head_to_head_record: 0.76, captain_potential: 0.55, ownership_projection: 24.3, price_efficiency: 0.62, upset_potential: 0.47, recent_match_points: [36, 26, 39, 23, 31], match_format_preference: 'Test', playing_conditions_preference: 'Day' },
  { name: 'A Rashid', full_name: 'Adil Rashid', team_name: 'England', player_role: 'BWL', credits: 7.5, selection_percentage: 42.8, points: 27, is_playing_today: true, country: 'England', batting_style: 'RH', bowling_style: 'RH', dream_team_percentage: 33.7, recent_form_rating: 0.72, consistency_score: 0.76, versatility_score: 0.84, injury_risk_score: 8, venue_performance: 0.74, pitch_suitability: 0.87, weather_adaptability: 0.73, opposition_strength: 0.75, head_to_head_record: 0.73, captain_potential: 0.48, ownership_projection: 21.4, price_efficiency: 0.57, upset_potential: 0.44, recent_match_points: [32, 22, 35, 19, 27], match_format_preference: 'ODI', playing_conditions_preference: 'Day' },
  { name: 'Z Crawley', full_name: 'Zak Crawley', team_name: 'England', player_role: 'BAT', credits: 7.0, selection_percentage: 38.4, points: 25, is_playing_today: true, country: 'England', batting_style: 'RH', bowling_style: 'RH', dream_team_percentage: 29.8, recent_form_rating: 0.68, consistency_score: 0.65, versatility_score: 0.75, injury_risk_score: 9, venue_performance: 0.70, pitch_suitability: 0.76, weather_adaptability: 0.69, opposition_strength: 0.71, head_to_head_record: 0.68, captain_potential: 0.58, ownership_projection: 19.2, price_efficiency: 0.57, upset_potential: 0.61, recent_match_points: [30, 20, 33, 17, 25], match_format_preference: 'Test', playing_conditions_preference: 'Day' },
  { name: 'M Ali', full_name: 'Moeen Ali', team_name: 'England', player_role: 'AR', credits: 7.5, selection_percentage: 44.2, points: 29, is_playing_today: true, country: 'England', batting_style: 'LH', bowling_style: 'RH', dream_team_percentage: 35.6, recent_form_rating: 0.73, consistency_score: 0.77, versatility_score: 0.88, injury_risk_score: 7, venue_performance: 0.75, pitch_suitability: 0.83, weather_adaptability: 0.76, opposition_strength: 0.76, head_to_head_record: 0.74, captain_potential: 0.71, ownership_projection: 22.6, price_efficiency: 0.58, upset_potential: 0.49, recent_match_points: [34, 24, 37, 21, 29], match_format_preference: 'Test', playing_conditions_preference: 'Day' },
  { name: 'S Broad', full_name: 'Stuart Broad', team_name: 'England', player_role: 'BWL', credits: 7.0, selection_percentage: 36.9, points: 23, is_playing_today: true, country: 'England', batting_style: 'LH', bowling_style: 'RH', dream_team_percentage: 28.4, recent_form_rating: 0.69, consistency_score: 0.82, versatility_score: 0.74, injury_risk_score: 6, venue_performance: 0.78, pitch_suitability: 0.85, weather_adaptability: 0.75, opposition_strength: 0.77, head_to_head_record: 0.79, captain_potential: 0.61, ownership_projection: 18.4, price_efficiency: 0.52, upset_potential: 0.42, recent_match_points: [28, 18, 31, 15, 23], match_format_preference: 'Test', playing_conditions_preference: 'Day' },
  { name: 'L Livingstone', full_name: 'Liam Livingstone', team_name: 'England', player_role: 'AR', credits: 6.5, selection_percentage: 34.7, points: 21, is_playing_today: true, country: 'England', batting_style: 'RH', bowling_style: 'RH', dream_team_percentage: 26.8, recent_form_rating: 0.71, consistency_score: 0.68, versatility_score: 0.82, injury_risk_score: 8, venue_performance: 0.72, pitch_suitability: 0.78, weather_adaptability: 0.71, opposition_strength: 0.73, head_to_head_record: 0.70, captain_potential: 0.65, ownership_projection: 17.3, price_efficiency: 0.51, upset_potential: 0.58, recent_match_points: [26, 16, 29, 13, 21], match_format_preference: 'T20', playing_conditions_preference: 'Night' },
  // Inactive players
  { name: 'J Bairstow', full_name: 'Jonny Bairstow', team_name: 'England', player_role: 'WK', credits: 6.0, selection_percentage: 19.8, points: 18, is_playing_today: false, country: 'England', batting_style: 'RH', bowling_style: 'RH', dream_team_percentage: 15.2, recent_form_rating: 0.63, consistency_score: 0.61, versatility_score: 0.76, injury_risk_score: 7, venue_performance: 0.65, pitch_suitability: 0.70, weather_adaptability: 0.64, opposition_strength: 0.66, head_to_head_record: 0.63, captain_potential: 0.52, ownership_projection: 9.9, price_efficiency: 0.48, upset_potential: 0.73, recent_match_points: [22, 14, 25, 11, 18], match_format_preference: 'Test', playing_conditions_preference: 'Day' },
  { name: 'C Woakes', full_name: 'Chris Woakes', team_name: 'England', player_role: 'AR', credits: 6.5, selection_percentage: 25.6, points: 22, is_playing_today: false, country: 'England', batting_style: 'RH', bowling_style: 'RH', dream_team_percentage: 19.8, recent_form_rating: 0.67, consistency_score: 0.73, versatility_score: 0.79, injury_risk_score: 6, venue_performance: 0.71, pitch_suitability: 0.78, weather_adaptability: 0.68, opposition_strength: 0.72, head_to_head_record: 0.70, captain_potential: 0.64, ownership_projection: 12.8, price_efficiency: 0.54, upset_potential: 0.65, recent_match_points: [27, 17, 30, 14, 22], match_format_preference: 'Test', playing_conditions_preference: 'Day' },
  { name: 'R Topley', full_name: 'Reece Topley', team_name: 'England', player_role: 'BWL', credits: 5.5, selection_percentage: 14.2, points: 16, is_playing_today: false, country: 'England', batting_style: 'LH', bowling_style: 'LH', dream_team_percentage: 10.9, recent_form_rating: 0.59, consistency_score: 0.64, versatility_score: 0.72, injury_risk_score: 5, venue_performance: 0.61, pitch_suitability: 0.73, weather_adaptability: 0.58, opposition_strength: 0.62, head_to_head_record: 0.59, captain_potential: 0.38, ownership_projection: 7.1, price_efficiency: 0.46, upset_potential: 0.79, recent_match_points: [19, 13, 22, 10, 16], match_format_preference: 'ODI', playing_conditions_preference: 'Day' },
  { name: 'P Salt', full_name: 'Phil Salt', team_name: 'England', player_role: 'WK', credits: 6.0, selection_percentage: 17.4, points: 15, is_playing_today: false, country: 'England', batting_style: 'RH', bowling_style: 'RH', dream_team_percentage: 13.4, recent_form_rating: 0.61, consistency_score: 0.57, versatility_score: 0.74, injury_risk_score: 9, venue_performance: 0.63, pitch_suitability: 0.68, weather_adaptability: 0.61, opposition_strength: 0.64, head_to_head_record: 0.61, captain_potential: 0.49, ownership_projection: 8.7, price_efficiency: 0.40, upset_potential: 0.82, recent_match_points: [18, 12, 21, 9, 15], match_format_preference: 'T20', playing_conditions_preference: 'Night' },

  // Pakistan Team (15 players - 11 active, 4 inactive)
  { name: 'B Azam', full_name: 'Babar Azam', team_name: 'Pakistan', player_role: 'BAT', credits: 11.0, selection_percentage: 81.5, points: 54, is_playing_today: true, country: 'Pakistan', batting_style: 'RH', bowling_style: 'RH', dream_team_percentage: 71.2, recent_form_rating: 0.91, consistency_score: 0.94, versatility_score: 0.93, injury_risk_score: 9, venue_performance: 0.89, pitch_suitability: 0.92, weather_adaptability: 0.87, opposition_strength: 0.90, head_to_head_record: 0.88, captain_potential: 0.96, ownership_projection: 40.8, price_efficiency: 0.74, upset_potential: 0.29, recent_match_points: [61, 47, 64, 43, 54], match_format_preference: 'ODI', playing_conditions_preference: 'Day' },
  { name: 'S Afridi', full_name: 'Shaheen Afridi', team_name: 'Pakistan', player_role: 'BWL', credits: 9.5, selection_percentage: 67.8, points: 41, is_playing_today: true, country: 'Pakistan', batting_style: 'LH', bowling_style: 'LH', dream_team_percentage: 58.4, recent_form_rating: 0.86, consistency_score: 0.84, versatility_score: 0.87, injury_risk_score: 7, venue_performance: 0.83, pitch_suitability: 0.89, weather_adaptability: 0.85, opposition_strength: 0.87, head_to_head_record: 0.84, captain_potential: 0.78, ownership_projection: 33.9, price_efficiency: 0.65, upset_potential: 0.40, recent_match_points: [47, 35, 50, 32, 41], match_format_preference: 'T20', playing_conditions_preference: 'Night' },
  { name: 'M Rizwan', full_name: 'Mohammad Rizwan', team_name: 'Pakistan', player_role: 'WK', credits: 9.0, selection_percentage: 63.2, points: 37, is_playing_today: true, country: 'Pakistan', batting_style: 'RH', bowling_style: 'RH', dream_team_percentage: 52.7, recent_form_rating: 0.82, consistency_score: 0.87, versatility_score: 0.85, injury_risk_score: 8, venue_performance: 0.80, pitch_suitability: 0.84, weather_adaptability: 0.82, opposition_strength: 0.83, head_to_head_record: 0.81, captain_potential: 0.85, ownership_projection: 31.6, price_efficiency: 0.62, upset_potential: 0.43, recent_match_points: [42, 32, 45, 29, 37], match_format_preference: 'T20', playing_conditions_preference: 'Night' },
  { name: 'F Zaman', full_name: 'Fakhar Zaman', team_name: 'Pakistan', player_role: 'BAT', credits: 8.5, selection_percentage: 56.4, points: 33, is_playing_today: true, country: 'Pakistan', batting_style: 'LH', bowling_style: 'LH', dream_team_percentage: 46.3, recent_form_rating: 0.78, consistency_score: 0.75, versatility_score: 0.81, injury_risk_score: 7, venue_performance: 0.76, pitch_suitability: 0.80, weather_adaptability: 0.78, opposition_strength: 0.79, head_to_head_record: 0.77, captain_potential: 0.69, ownership_projection: 28.2, price_efficiency: 0.58, upset_potential: 0.49, recent_match_points: [38, 28, 41, 25, 33], match_format_preference: 'ODI', playing_conditions_preference: 'Day' },
  { name: 'H Rauf', full_name: 'Haris Rauf', team_name: 'Pakistan', player_role: 'BWL', credits: 8.0, selection_percentage: 49.7, points: 30, is_playing_today: true, country: 'Pakistan', batting_style: 'RH', bowling_style: 'RH', dream_team_percentage: 40.8, recent_form_rating: 0.80, consistency_score: 0.77, versatility_score: 0.82, injury_risk_score: 6, venue_performance: 0.78, pitch_suitability: 0.83, weather_adaptability: 0.79, opposition_strength: 0.80, head_to_head_record: 0.78, captain_potential: 0.62, ownership_projection: 24.9, price_efficiency: 0.56, upset_potential: 0.51, recent_match_points: [35, 25, 38, 22, 30], match_format_preference: 'T20', playing_conditions_preference: 'Night' },
  { name: 'S Masood', full_name: 'Shan Masood', team_name: 'Pakistan', player_role: 'BAT', credits: 7.5, selection_percentage: 43.6, points: 26, is_playing_today: true, country: 'Pakistan', batting_style: 'LH', bowling_style: 'LH', dream_team_percentage: 35.9, recent_form_rating: 0.74, consistency_score: 0.79, versatility_score: 0.76, injury_risk_score: 8, venue_performance: 0.73, pitch_suitability: 0.77, weather_adaptability: 0.75, opposition_strength: 0.75, head_to_head_record: 0.73, captain_potential: 0.79, ownership_projection: 21.8, price_efficiency: 0.52, upset_potential: 0.46, recent_match_points: [30, 22, 33, 19, 26], match_format_preference: 'Test', playing_conditions_preference: 'Day' },
  { name: 'I Ahmed', full_name: 'Iftikhar Ahmed', team_name: 'Pakistan', player_role: 'AR', credits: 7.0, selection_percentage: 38.9, points: 24, is_playing_today: true, country: 'Pakistan', batting_style: 'RH', bowling_style: 'RH', dream_team_percentage: 31.6, recent_form_rating: 0.71, consistency_score: 0.74, versatility_score: 0.79, injury_risk_score: 8, venue_performance: 0.72, pitch_suitability: 0.76, weather_adaptability: 0.73, opposition_strength: 0.74, head_to_head_record: 0.72, captain_potential: 0.67, ownership_projection: 19.4, price_efficiency: 0.51, upset_potential: 0.54, recent_match_points: [28, 20, 31, 17, 24], match_format_preference: 'ODI', playing_conditions_preference: 'Day' },
  { name: 'N Shah', full_name: 'Naseem Shah', team_name: 'Pakistan', player_role: 'BWL', credits: 7.5, selection_percentage: 41.8, points: 27, is_playing_today: true, country: 'Pakistan', batting_style: 'RH', bowling_style: 'RH', dream_team_percentage: 34.2, recent_form_rating: 0.76, consistency_score: 0.81, versatility_score: 0.78, injury_risk_score: 7, venue_performance: 0.75, pitch_suitability: 0.82, weather_adaptability: 0.77, opposition_strength: 0.78, head_to_head_record: 0.76, captain_potential: 0.58, ownership_projection: 20.9, price_efficiency: 0.54, upset_potential: 0.48, recent_match_points: [31, 23, 34, 20, 27], match_format_preference: 'Test', playing_conditions_preference: 'Day' },
  { name: 'S Khan', full_name: 'Shadab Khan', team_name: 'Pakistan', player_role: 'AR', credits: 8.0, selection_percentage: 47.3, points: 29, is_playing_today: true, country: 'Pakistan', batting_style: 'RH', bowling_style: 'RH', dream_team_percentage: 38.6, recent_form_rating: 0.77, consistency_score: 0.76, versatility_score: 0.84, injury_risk_score: 7, venue_performance: 0.75, pitch_suitability: 0.81, weather_adaptability: 0.78, opposition_strength: 0.77, head_to_head_record: 0.75, captain_potential: 0.81, ownership_projection: 23.7, price_efficiency: 0.55, upset_potential: 0.50, recent_match_points: [33, 25, 36, 22, 29], match_format_preference: 'T20', playing_conditions_preference: 'Night' },
  { name: 'M Nawaz', full_name: 'Mohammad Nawaz', team_name: 'Pakistan', player_role: 'AR', credits: 6.5, selection_percentage: 35.7, points: 22, is_playing_today: true, country: 'Pakistan', batting_style: 'LH', bowling_style: 'LH', dream_team_percentage: 28.9, recent_form_rating: 0.69, consistency_score: 0.72, versatility_score: 0.77, injury_risk_score: 8, venue_performance: 0.71, pitch_suitability: 0.78, weather_adaptability: 0.70, opposition_strength: 0.72, head_to_head_record: 0.70, captain_potential: 0.64, ownership_projection: 17.8, price_efficiency: 0.51, upset_potential: 0.57, recent_match_points: [26, 18, 29, 15, 22], match_format_preference: 'ODI', playing_conditions_preference: 'Day' },
  { name: 'I ul Haq', full_name: 'Imam ul Haq', team_name: 'Pakistan', player_role: 'BAT', credits: 7.0, selection_percentage: 39.8, points: 25, is_playing_today: true, country: 'Pakistan', batting_style: 'LH', bowling_style: 'LH', dream_team_percentage: 32.4, recent_form_rating: 0.72, consistency_score: 0.76, versatility_score: 0.74, injury_risk_score: 9, venue_performance: 0.74, pitch_suitability: 0.78, weather_adaptability: 0.72, opposition_strength: 0.74, head_to_head_record: 0.72, captain_potential: 0.66, ownership_projection: 19.9, price_efficiency: 0.54, upset_potential: 0.53, recent_match_points: [29, 21, 32, 18, 25], match_format_preference: 'ODI', playing_conditions_preference: 'Day' },
  // Inactive players
  { name: 'A Ali', full_name: 'Azam Ali', team_name: 'Pakistan', player_role: 'BAT', credits: 6.0, selection_percentage: 18.9, points: 17, is_playing_today: false, country: 'Pakistan', batting_style: 'RH', bowling_style: 'RH', dream_team_percentage: 14.6, recent_form_rating: 0.61, consistency_score: 0.64, versatility_score: 0.68, injury_risk_score: 8, venue_performance: 0.63, pitch_suitability: 0.67, weather_adaptability: 0.62, opposition_strength: 0.64, head_to_head_record: 0.62, captain_potential: 0.51, ownership_projection: 9.4, price_efficiency: 0.45, upset_potential: 0.73, recent_match_points: [20, 14, 23, 11, 17], match_format_preference: 'T20', playing_conditions_preference: 'Night' },
  { name: 'M Hasnain', full_name: 'Mohammad Hasnain', team_name: 'Pakistan', player_role: 'BWL', credits: 5.5, selection_percentage: 15.4, points: 14, is_playing_today: false, country: 'Pakistan', batting_style: 'RH', bowling_style: 'RH', dream_team_percentage: 11.8, recent_form_rating: 0.58, consistency_score: 0.61, versatility_score: 0.65, injury_risk_score: 7, venue_performance: 0.60, pitch_suitability: 0.68, weather_adaptability: 0.59, opposition_strength: 0.61, head_to_head_record: 0.59, captain_potential: 0.41, ownership_projection: 7.7, price_efficiency: 0.41, upset_potential: 0.76, recent_match_points: [17, 11, 20, 8, 14], match_format_preference: 'T20', playing_conditions_preference: 'Night' },
  { name: 'U Qadir', full_name: 'Usman Qadir', team_name: 'Pakistan', player_role: 'BWL', credits: 5.0, selection_percentage: 12.8, points: 11, is_playing_today: false, country: 'Pakistan', batting_style: 'RH', bowling_style: 'RH', dream_team_percentage: 9.6, recent_form_rating: 0.54, consistency_score: 0.58, versatility_score: 0.62, injury_risk_score: 9, venue_performance: 0.56, pitch_suitability: 0.65, weather_adaptability: 0.55, opposition_strength: 0.57, head_to_head_record: 0.55, captain_potential: 0.36, ownership_projection: 6.4, price_efficiency: 0.35, upset_potential: 0.81, recent_match_points: [14, 8, 17, 5, 11], match_format_preference: 'ODI', playing_conditions_preference: 'Day' },
  { name: 'K Shah', full_name: 'Khushdil Shah', team_name: 'Pakistan', player_role: 'AR', credits: 5.5, selection_percentage: 16.7, points: 13, is_playing_today: false, country: 'Pakistan', batting_style: 'LH', bowling_style: 'LH', dream_team_percentage: 12.4, recent_form_rating: 0.59, consistency_score: 0.62, versatility_score: 0.69, injury_risk_score: 8, venue_performance: 0.61, pitch_suitability: 0.66, weather_adaptability: 0.60, opposition_strength: 0.62, head_to_head_record: 0.60, captain_potential: 0.44, ownership_projection: 8.3, price_efficiency: 0.38, upset_potential: 0.77, recent_match_points: [16, 10, 19, 7, 13], match_format_preference: 'T20', playing_conditions_preference: 'Night' },

  // South Africa Team (15 players - 11 active, 4 inactive)
  { name: 'Q de Kock', full_name: 'Quinton de Kock', team_name: 'South Africa', player_role: 'WK', credits: 10.0, selection_percentage: 74.6, points: 47, is_playing_today: true, country: 'South Africa', batting_style: 'LH', bowling_style: 'RH' },
  { name: 'K Rabada', full_name: 'Kagiso Rabada', team_name: 'South Africa', player_role: 'BWL', credits: 9.5, selection_percentage: 69.8, points: 42, is_playing_today: true, country: 'South Africa', batting_style: 'RH', bowling_style: 'RH' },
  { name: 'A Markram', full_name: 'Aiden Markram', team_name: 'South Africa', player_role: 'BAT', credits: 9.0, selection_percentage: 62.4, points: 38, is_playing_today: true, country: 'South Africa', batting_style: 'RH', bowling_style: 'RH' },
  { name: 'D Miller', full_name: 'David Miller', team_name: 'South Africa', player_role: 'BAT', credits: 8.5, selection_percentage: 57.9, points: 35, is_playing_today: true, country: 'South Africa', batting_style: 'LH', bowling_style: 'LH' },
  { name: 'A Nortje', full_name: 'Anrich Nortje', team_name: 'South Africa', player_role: 'BWL', credits: 8.0, selection_percentage: 51.3, points: 32, is_playing_today: true, country: 'South Africa', batting_style: 'RH', bowling_style: 'RH' },
  { name: 'T Bavuma', full_name: 'Temba Bavuma', team_name: 'South Africa', player_role: 'BAT', credits: 7.5, selection_percentage: 45.7, points: 28, is_playing_today: true, country: 'South Africa', batting_style: 'RH', bowling_style: 'RH' },
  { name: 'K Maharaj', full_name: 'Keshav Maharaj', team_name: 'South Africa', player_role: 'BWL', credits: 7.0, selection_percentage: 39.8, points: 25, is_playing_today: true, country: 'South Africa', batting_style: 'LH', bowling_style: 'LH' },
  { name: 'H Klaasen', full_name: 'Heinrich Klaasen', team_name: 'South Africa', player_role: 'WK', credits: 7.5, selection_percentage: 43.2, points: 27, is_playing_today: true, country: 'South Africa', batting_style: 'RH', bowling_style: 'RH' },
  { name: 'M Jansen', full_name: 'Marco Jansen', team_name: 'South Africa', player_role: 'AR', credits: 7.0, selection_percentage: 37.6, points: 23, is_playing_today: true, country: 'South Africa', batting_style: 'LH', bowling_style: 'LH' },
  { name: 'T Shamsi', full_name: 'Tabraiz Shamsi', team_name: 'South Africa', player_role: 'BWL', credits: 6.5, selection_percentage: 33.4, points: 21, is_playing_today: true, country: 'South Africa', batting_style: 'LH', bowling_style: 'LH' },
  { name: 'L Ngidi', full_name: 'Lungi Ngidi', team_name: 'South Africa', player_role: 'BWL', credits: 6.5, selection_percentage: 35.8, points: 22, is_playing_today: true, country: 'South Africa', batting_style: 'RH', bowling_style: 'RH' },
  // Inactive players
  { name: 'R van der Dussen', full_name: 'Rassie van der Dussen', team_name: 'South Africa', player_role: 'BAT', credits: 6.0, selection_percentage: 21.5, points: 19, is_playing_today: false, country: 'South Africa', batting_style: 'RH', bowling_style: 'RH' },
  { name: 'W Mulder', full_name: 'Wiaan Mulder', team_name: 'South Africa', player_role: 'AR', credits: 5.5, selection_percentage: 17.8, points: 16, is_playing_today: false, country: 'South Africa', batting_style: 'RH', bowling_style: 'RH' },
  { name: 'B Fortuin', full_name: 'Bjorn Fortuin', team_name: 'South Africa', player_role: 'BWL', credits: 5.0, selection_percentage: 14.2, points: 13, is_playing_today: false, country: 'South Africa', batting_style: 'LH', bowling_style: 'LH' },
  { name: 'J Malan', full_name: 'Janneman Malan', team_name: 'South Africa', player_role: 'BAT', credits: 5.5, selection_percentage: 16.9, points: 15, is_playing_today: false, country: 'South Africa', batting_style: 'RH', bowling_style: 'RH' },

  // New Zealand Team (15 players - 11 active, 4 inactive)
  { name: 'K Williamson', full_name: 'Kane Williamson', team_name: 'New Zealand', player_role: 'BAT', credits: 10.5, selection_percentage: 77.3, points: 49, is_playing_today: true, country: 'New Zealand', batting_style: 'RH', bowling_style: 'RH' },
  { name: 'T Boult', full_name: 'Trent Boult', team_name: 'New Zealand', player_role: 'BWL', credits: 9.0, selection_percentage: 64.7, points: 39, is_playing_today: true, country: 'New Zealand', batting_style: 'LH', bowling_style: 'LH' },
  { name: 'D Conway', full_name: 'Devon Conway', team_name: 'New Zealand', player_role: 'WK', credits: 8.5, selection_percentage: 58.9, points: 36, is_playing_today: true, country: 'New Zealand', batting_style: 'LH', bowling_style: 'RH' },
  { name: 'T Southee', full_name: 'Tim Southee', team_name: 'New Zealand', player_role: 'BWL', credits: 8.0, selection_percentage: 52.6, points: 33, is_playing_today: true, country: 'New Zealand', batting_style: 'RH', bowling_style: 'RH' },
  { name: 'G Phillips', full_name: 'Glenn Phillips', team_name: 'New Zealand', player_role: 'AR', credits: 7.5, selection_percentage: 46.8, points: 29, is_playing_today: true, country: 'New Zealand', batting_style: 'RH', bowling_style: 'RH' },
  { name: 'D Mitchell', full_name: 'Daryl Mitchell', team_name: 'New Zealand', player_role: 'AR', credits: 7.0, selection_percentage: 41.2, points: 26, is_playing_today: true, country: 'New Zealand', batting_style: 'RH', bowling_style: 'RH' },
  { name: 'M Santner', full_name: 'Mitchell Santner', team_name: 'New Zealand', player_role: 'AR', credits: 6.5, selection_percentage: 37.4, points: 23, is_playing_today: true, country: 'New Zealand', batting_style: 'LH', bowling_style: 'LH' },
  { name: 'T Latham', full_name: 'Tom Latham', team_name: 'New Zealand', player_role: 'WK', credits: 7.0, selection_percentage: 39.6, points: 25, is_playing_today: true, country: 'New Zealand', batting_style: 'LH', bowling_style: 'RH' },
  { name: 'K Jamieson', full_name: 'Kyle Jamieson', team_name: 'New Zealand', player_role: 'BWL', credits: 6.5, selection_percentage: 35.8, points: 22, is_playing_today: true, country: 'New Zealand', batting_style: 'RH', bowling_style: 'RH' },
  { name: 'R Ravindra', full_name: 'Rachin Ravindra', team_name: 'New Zealand', player_role: 'AR', credits: 6.0, selection_percentage: 32.4, points: 20, is_playing_today: true, country: 'New Zealand', batting_style: 'LH', bowling_style: 'LH' },
  { name: 'M Henry', full_name: 'Matt Henry', team_name: 'New Zealand', player_role: 'BWL', credits: 6.0, selection_percentage: 30.7, points: 19, is_playing_today: true, country: 'New Zealand', batting_style: 'RH', bowling_style: 'RH' },
  // Inactive players
  { name: 'C de Grandhomme', full_name: 'Colin de Grandhomme', team_name: 'New Zealand', player_role: 'AR', credits: 5.5, selection_percentage: 18.9, points: 17, is_playing_today: false, country: 'New Zealand', batting_style: 'RH', bowling_style: 'RH' },
  { name: 'A Milne', full_name: 'Adam Milne', team_name: 'New Zealand', player_role: 'BWL', credits: 5.0, selection_percentage: 15.6, points: 14, is_playing_today: false, country: 'New Zealand', batting_style: 'RH', bowling_style: 'RH' },
  { name: 'I Sodhi', full_name: 'Ish Sodhi', team_name: 'New Zealand', player_role: 'BWL', credits: 5.5, selection_percentage: 17.3, points: 16, is_playing_today: false, country: 'New Zealand', batting_style: 'RH', bowling_style: 'RH' },
  { name: 'M Bracewell', full_name: 'Michael Bracewell', team_name: 'New Zealand', player_role: 'AR', credits: 5.0, selection_percentage: 13.8, points: 12, is_playing_today: false, country: 'New Zealand', batting_style: 'LH', bowling_style: 'RH' },

  // West Indies Team (15 players - 11 active, 4 inactive)
  { name: 'S Hope', full_name: 'Shai Hope', team_name: 'West Indies', player_role: 'WK', credits: 9.0, selection_percentage: 66.8, points: 40, is_playing_today: true, country: 'West Indies', batting_style: 'RH', bowling_style: 'RH' },
  { name: 'J Holder', full_name: 'Jason Holder', team_name: 'West Indies', player_role: 'AR', credits: 8.5, selection_percentage: 59.4, points: 36, is_playing_today: true, country: 'West Indies', batting_style: 'RH', bowling_style: 'RH' },
  { name: 'S Hetmyer', full_name: 'Shimron Hetmyer', team_name: 'West Indies', player_role: 'BAT', credits: 8.0, selection_percentage: 53.7, points: 32, is_playing_today: true, country: 'West Indies', batting_style: 'LH', bowling_style: 'RH' },
  { name: 'A Russell', full_name: 'Andre Russell', team_name: 'West Indies', player_role: 'AR', credits: 8.5, selection_percentage: 61.2, points: 37, is_playing_today: true, country: 'West Indies', batting_style: 'RH', bowling_style: 'RH' },
  { name: 'A Joseph', full_name: 'Alzarri Joseph', team_name: 'West Indies', player_role: 'BWL', credits: 7.5, selection_percentage: 47.9, points: 29, is_playing_today: true, country: 'West Indies', batting_style: 'RH', bowling_style: 'RH' },
  { name: 'K Pollard', full_name: 'Kieron Pollard', team_name: 'West Indies', player_role: 'AR', credits: 7.0, selection_percentage: 42.6, points: 26, is_playing_today: true, country: 'West Indies', batting_style: 'RH', bowling_style: 'RH' },
  { name: 'R Shepherd', full_name: 'Romario Shepherd', team_name: 'West Indies', player_role: 'AR', credits: 6.5, selection_percentage: 38.4, points: 23, is_playing_today: true, country: 'West Indies', batting_style: 'RH', bowling_style: 'RH' },
  { name: 'K Roach', full_name: 'Kemar Roach', team_name: 'West Indies', player_role: 'BWL', credits: 6.5, selection_percentage: 36.8, points: 22, is_playing_today: true, country: 'West Indies', batting_style: 'RH', bowling_style: 'RH' },
  { name: 'N Pooran', full_name: 'Nicholas Pooran', team_name: 'West Indies', player_role: 'WK', credits: 7.5, selection_percentage: 45.3, points: 28, is_playing_today: true, country: 'West Indies', batting_style: 'LH', bowling_style: 'RH' },
  { name: 'A Hosein', full_name: 'Akeal Hosein', team_name: 'West Indies', player_role: 'BWL', credits: 6.0, selection_percentage: 33.7, points: 20, is_playing_today: true, country: 'West Indies', batting_style: 'LH', bowling_style: 'LH' },
  { name: 'B King', full_name: 'Brandon King', team_name: 'West Indies', player_role: 'BAT', credits: 6.0, selection_percentage: 31.9, points: 19, is_playing_today: true, country: 'West Indies', batting_style: 'RH', bowling_style: 'RH' },
  // Inactive players
  { name: 'E Lewis', full_name: 'Evin Lewis', team_name: 'West Indies', player_role: 'BAT', credits: 5.5, selection_percentage: 19.8, points: 17, is_playing_today: false, country: 'West Indies', batting_style: 'LH', bowling_style: 'RH' },
  { name: 'O McCoy', full_name: 'Obed McCoy', team_name: 'West Indies', player_role: 'BWL', credits: 5.0, selection_percentage: 16.4, points: 15, is_playing_today: false, country: 'West Indies', batting_style: 'LH', bowling_style: 'LH' },
  { name: 'K Carty', full_name: 'Keacy Carty', team_name: 'West Indies', player_role: 'BAT', credits: 4.5, selection_percentage: 12.7, points: 11, is_playing_today: false, country: 'West Indies', batting_style: 'RH', bowling_style: 'RH' },
  { name: 'G Motie', full_name: 'Gudakesh Motie', team_name: 'West Indies', player_role: 'BWL', credits: 5.0, selection_percentage: 14.9, points: 13, is_playing_today: false, country: 'West Indies', batting_style: 'LH', bowling_style: 'LH' },

  // Sri Lanka Team (15 players - 11 active, 4 inactive)
  { name: 'K Mendis', full_name: 'Kusal Mendis', team_name: 'Sri Lanka', player_role: 'WK', credits: 8.5, selection_percentage: 61.4, points: 37, is_playing_today: true, country: 'Sri Lanka', batting_style: 'RH', bowling_style: 'RH' },
  { name: 'W Hasaranga', full_name: 'Wanindu Hasaranga', team_name: 'Sri Lanka', player_role: 'AR', credits: 8.0, selection_percentage: 56.8, points: 34, is_playing_today: true, country: 'Sri Lanka', batting_style: 'RH', bowling_style: 'RH' },
  { name: 'P Nissanka', full_name: 'Pathum Nissanka', team_name: 'Sri Lanka', player_role: 'BAT', credits: 7.5, selection_percentage: 49.6, points: 30, is_playing_today: true, country: 'Sri Lanka', batting_style: 'RH', bowling_style: 'RH' },
  { name: 'C Karunaratne', full_name: 'Chamika Karunaratne', team_name: 'Sri Lanka', player_role: 'AR', credits: 7.0, selection_percentage: 43.8, points: 26, is_playing_today: true, country: 'Sri Lanka', batting_style: 'RH', bowling_style: 'RH' },
  { name: 'M Theekshana', full_name: 'Maheesh Theekshana', team_name: 'Sri Lanka', player_role: 'BWL', credits: 6.5, selection_percentage: 39.7, points: 24, is_playing_today: true, country: 'Sri Lanka', batting_style: 'RH', bowling_style: 'RH' },
  { name: 'D Shanaka', full_name: 'Dasun Shanaka', team_name: 'Sri Lanka', player_role: 'AR', credits: 6.5, selection_percentage: 37.9, points: 23, is_playing_today: true, country: 'Sri Lanka', batting_style: 'RH', bowling_style: 'RH' },
  { name: 'L Kumara', full_name: 'Lahiru Kumara', team_name: 'Sri Lanka', player_role: 'BWL', credits: 6.0, selection_percentage: 34.6, points: 21, is_playing_today: true, country: 'Sri Lanka', batting_style: 'RH', bowling_style: 'RH' },
  { name: 'D de Silva', full_name: 'Dhananjaya de Silva', team_name: 'Sri Lanka', player_role: 'AR', credits: 6.0, selection_percentage: 32.8, points: 20, is_playing_today: true, country: 'Sri Lanka', batting_style: 'RH', bowling_style: 'RH' },
  { name: 'B Rajapaksa', full_name: 'Bhanuka Rajapaksa', team_name: 'Sri Lanka', player_role: 'BAT', credits: 5.5, selection_percentage: 29.4, points: 18, is_playing_today: true, country: 'Sri Lanka', batting_style: 'LH', bowling_style: 'RH' },
  { name: 'I Udana', full_name: 'Isuru Udana', team_name: 'Sri Lanka', player_role: 'BWL', credits: 5.5, selection_percentage: 27.6, points: 17, is_playing_today: true, country: 'Sri Lanka', batting_style: 'LH', bowling_style: 'LH' },
  { name: 'A Mathews', full_name: 'Angelo Mathews', team_name: 'Sri Lanka', player_role: 'AR', credits: 6.5, selection_percentage: 36.2, points: 22, is_playing_today: true, country: 'Sri Lanka', batting_style: 'RH', bowling_style: 'RH' },
  // Inactive players
  { name: 'K Perera', full_name: 'Kusal Perera', team_name: 'Sri Lanka', player_role: 'WK', credits: 5.0, selection_percentage: 18.7, points: 16, is_playing_today: false, country: 'Sri Lanka', batting_style: 'LH', bowling_style: 'RH' },
  { name: 'N Pradeep', full_name: 'Nuwan Pradeep', team_name: 'Sri Lanka', player_role: 'BWL', credits: 4.5, selection_percentage: 15.3, points: 13, is_playing_today: false, country: 'Sri Lanka', batting_style: 'RH', bowling_style: 'RH' },
  { name: 'P Jayawickrama', full_name: 'Praveen Jayawickrama', team_name: 'Sri Lanka', player_role: 'BWL', credits: 4.5, selection_percentage: 13.8, points: 12, is_playing_today: false, country: 'Sri Lanka', batting_style: 'LH', bowling_style: 'LH' },
  { name: 'C Asalanka', full_name: 'Charith Asalanka', team_name: 'Sri Lanka', player_role: 'BAT', credits: 5.0, selection_percentage: 16.9, points: 14, is_playing_today: false, country: 'Sri Lanka', batting_style: 'LH', bowling_style: 'LH' },

  // Bangladesh Team (15 players - 11 active, 4 inactive)
  { name: 'S Al Hasan', full_name: 'Shakib Al Hasan', team_name: 'Bangladesh', player_role: 'AR', credits: 9.5, selection_percentage: 73.6, points: 44, is_playing_today: true, country: 'Bangladesh', batting_style: 'LH', bowling_style: 'LH' },
  { name: 'M Rahim', full_name: 'Mushfiqur Rahim', team_name: 'Bangladesh', player_role: 'WK', credits: 8.5, selection_percentage: 62.9, points: 38, is_playing_today: true, country: 'Bangladesh', batting_style: 'RH', bowling_style: 'RH' },
  { name: 'L Das', full_name: 'Liton Das', team_name: 'Bangladesh', player_role: 'WK', credits: 7.5, selection_percentage: 51.7, points: 31, is_playing_today: true, country: 'Bangladesh', batting_style: 'RH', bowling_style: 'RH' },
  { name: 'T Iqbal', full_name: 'Tamim Iqbal', team_name: 'Bangladesh', player_role: 'BAT', credits: 8.0, selection_percentage: 56.3, points: 34, is_playing_today: true, country: 'Bangladesh', batting_style: 'LH', bowling_style: 'RH' },
  { name: 'M Rahman', full_name: 'Mustafizur Rahman', team_name: 'Bangladesh', player_role: 'BWL', credits: 7.5, selection_percentage: 47.8, points: 29, is_playing_today: true, country: 'Bangladesh', batting_style: 'LH', bowling_style: 'LH' },
  { name: 'M Miraz', full_name: 'Mehidy Hasan Miraz', team_name: 'Bangladesh', player_role: 'AR', credits: 7.0, selection_percentage: 42.6, points: 26, is_playing_today: true, country: 'Bangladesh', batting_style: 'RH', bowling_style: 'RH' },
  { name: 'A Hossain', full_name: 'Afif Hossain', team_name: 'Bangladesh', player_role: 'AR', credits: 6.5, selection_percentage: 38.9, points: 23, is_playing_today: true, country: 'Bangladesh', batting_style: 'LH', bowling_style: 'LH' },
  { name: 'T Ahmed', full_name: 'Taskin Ahmed', team_name: 'Bangladesh', player_role: 'BWL', credits: 6.5, selection_percentage: 36.4, points: 22, is_playing_today: true, country: 'Bangladesh', batting_style: 'RH', bowling_style: 'RH' },
  { name: 'N Shanto', full_name: 'Najmul Hossain Shanto', team_name: 'Bangladesh', player_role: 'BAT', credits: 6.0, selection_percentage: 33.7, points: 20, is_playing_today: true, country: 'Bangladesh', batting_style: 'LH', bowling_style: 'LH' },
  { name: 'S Sarkar', full_name: 'Soumya Sarkar', team_name: 'Bangladesh', player_role: 'AR', credits: 5.5, selection_percentage: 29.8, points: 18, is_playing_today: true, country: 'Bangladesh', batting_style: 'LH', bowling_style: 'RH' },
  { name: 'E Haque', full_name: 'Ebadot Hossain Chowdhury', team_name: 'Bangladesh', player_role: 'BWL', credits: 5.5, selection_percentage: 27.4, points: 17, is_playing_today: true, country: 'Bangladesh', batting_style: 'RH', bowling_style: 'RH' },
  // Inactive players
  { name: 'M Hasan', full_name: 'Mahedi Hasan', team_name: 'Bangladesh', player_role: 'AR', credits: 5.0, selection_percentage: 19.6, points: 16, is_playing_today: false, country: 'Bangladesh', batting_style: 'RH', bowling_style: 'RH' },
  { name: 'S Islam', full_name: 'Shoriful Islam', team_name: 'Bangladesh', player_role: 'BWL', credits: 4.5, selection_percentage: 16.8, points: 14, is_playing_today: false, country: 'Bangladesh', batting_style: 'LH', bowling_style: 'LH' },
  { name: 'Y Mahmud', full_name: 'Yasir Ali Chowdhury', team_name: 'Bangladesh', player_role: 'BAT', credits: 4.5, selection_percentage: 14.2, points: 12, is_playing_today: false, country: 'Bangladesh', batting_style: 'RH', bowling_style: 'RH' },
  { name: 'N Ahmed', full_name: 'Nasum Ahmed', team_name: 'Bangladesh', player_role: 'BWL', credits: 4.0, selection_percentage: 11.7, points: 10, is_playing_today: false, country: 'Bangladesh', batting_style: 'LH', bowling_style: 'LH' },

  // Afghanistan Team (15 players - 11 active, 4 inactive)
  { name: 'R Khan', full_name: 'Rashid Khan', team_name: 'Afghanistan', player_role: 'AR', credits: 9.0, selection_percentage: 68.9, points: 41, is_playing_today: true, country: 'Afghanistan', batting_style: 'RH', bowling_style: 'RH' },
  { name: 'M Nabi', full_name: 'Mohammad Nabi', team_name: 'Afghanistan', player_role: 'AR', credits: 8.0, selection_percentage: 57.6, points: 35, is_playing_today: true, country: 'Afghanistan', batting_style: 'RH', bowling_style: 'RH' },
  { name: 'H Zazai', full_name: 'Hazratullah Zazai', team_name: 'Afghanistan', player_role: 'BAT', credits: 7.5, selection_percentage: 49.8, points: 30, is_playing_today: true, country: 'Afghanistan', batting_style: 'LH', bowling_style: 'RH' },
  { name: 'R Gurbaz', full_name: 'Rahmanullah Gurbaz', team_name: 'Afghanistan', player_role: 'WK', credits: 7.0, selection_percentage: 44.7, points: 27, is_playing_today: true, country: 'Afghanistan', batting_style: 'RH', bowling_style: 'RH' },
  { name: 'F Ahmad', full_name: 'Fazalhaq Farooqi', team_name: 'Afghanistan', player_role: 'BWL', credits: 6.5, selection_percentage: 39.4, points: 24, is_playing_today: true, country: 'Afghanistan', batting_style: 'LH', bowling_style: 'LH' },
  { name: 'I Alikhil', full_name: 'Ikram Alikhil', team_name: 'Afghanistan', player_role: 'WK', credits: 6.0, selection_percentage: 35.8, points: 21, is_playing_today: true, country: 'Afghanistan', batting_style: 'LH', bowling_style: 'RH' },
  { name: 'A Omarzai', full_name: 'Azmatullah Omarzai', team_name: 'Afghanistan', player_role: 'AR', credits: 6.0, selection_percentage: 33.6, points: 20, is_playing_today: true, country: 'Afghanistan', batting_style: 'RH', bowling_style: 'RH' },
  { name: 'M Ur Rahman', full_name: 'Mujeeb Ur Rahman', team_name: 'Afghanistan', player_role: 'BWL', credits: 5.5, selection_percentage: 30.7, points: 18, is_playing_today: true, country: 'Afghanistan', batting_style: 'RH', bowling_style: 'RH' },
  { name: 'N Kharoti', full_name: 'Nangeyalia Kharoti', team_name: 'Afghanistan', player_role: 'BWL', credits: 5.0, selection_percentage: 27.3, points: 16, is_playing_today: true, country: 'Afghanistan', batting_style: 'RH', bowling_style: 'RH' },
  { name: 'I Zadran', full_name: 'Ibrahim Zadran', team_name: 'Afghanistan', player_role: 'BAT', credits: 5.5, selection_percentage: 29.8, points: 17, is_playing_today: true, country: 'Afghanistan', batting_style: 'RH', bowling_style: 'RH' },
  { name: 'G Naib', full_name: 'Gulbadin Naib', team_name: 'Afghanistan', player_role: 'AR', credits: 5.0, selection_percentage: 25.9, points: 15, is_playing_today: true, country: 'Afghanistan', batting_style: 'RH', bowling_style: 'RH' },
  // Inactive players
  { name: 'A Afghan', full_name: 'Asghar Afghan', team_name: 'Afghanistan', player_role: 'BAT', credits: 4.5, selection_percentage: 17.8, points: 14, is_playing_today: false, country: 'Afghanistan', batting_style: 'RH', bowling_style: 'RH' },
  { name: 'H Shahidi', full_name: 'Hashmatullah Shahidi', team_name: 'Afghanistan', player_role: 'BAT', credits: 4.5, selection_percentage: 16.2, points: 13, is_playing_today: false, country: 'Afghanistan', batting_style: 'LH', bowling_style: 'RH' },
  { name: 'W Riaz', full_name: 'Wafadar Momand', team_name: 'Afghanistan', player_role: 'BWL', credits: 4.0, selection_percentage: 13.7, points: 11, is_playing_today: false, country: 'Afghanistan', batting_style: 'RH', bowling_style: 'RH' },
  { name: 'Q Ahmad', full_name: 'Qais Ahmad', team_name: 'Afghanistan', player_role: 'BWL', credits: 4.0, selection_percentage: 12.4, points: 10, is_playing_today: false, country: 'Afghanistan', batting_style: 'RH', bowling_style: 'RH' }
];

async function insertDummyData() {
  console.log('🚀 Starting dummy data insertion...');
  
  try {
    // Insert matches
    console.log('📊 Inserting matches...');
    for (const match of dummyMatches) {
      const insertedMatch = await neonDB.insertMatch(match);
      console.log(`✅ Inserted match: ${insertedMatch.team_name}`);
    }

    // Insert players
    console.log('👥 Inserting players...');
    for (const player of dummyPlayers) {
      const insertedPlayer = await neonDB.insertPlayer(player);
      console.log(`✅ Inserted player: ${insertedPlayer.name} (${insertedPlayer.team_name})`);
    }

    console.log('🎉 Dummy data insertion completed successfully!');
    
    // Verify data
    const matches = await neonDB.getAllMatches();
    const players = await neonDB.getAllPlayers();
    console.log(`📈 Summary: ${matches.length} matches and ${players.length} players inserted.`);
    
  } catch (error) {
    console.error('❌ Error inserting dummy data:', error);
  }
}

// Run the script
if (require.main === module) {
  insertDummyData().then(() => {
    console.log('Script completed.');
    process.exit(0);
  }).catch((error) => {
    console.error('Script failed:', error);
    process.exit(1);
  });
}

export { insertDummyData };
